# Example configuration using file includes to simulate CVE-2020-3452
---
states:
  _START:
  - pattern: '/\+CSCOT\+/translation-table\?type=mst&textdomain=/%2bCSCOE%2b/portal_inc.lua&default-language&lang='
    next: 'http-200-mst'
  - pattern: '/\+CSCOT\+/oem-customization\?app=AnyConnect&type=oem&platform=..&resource-type=..&name=%2bCSCOE%2b/portal_inc.lua'
    file: 'configs/CVE-2020-3452/oem.txt'
    next: 'http-200-oem'
  - pattern: .*
    next: 'http-404'
  # http-200-mst state collects input until it gets a blank line and then
  # returns content
  http-200-mst:
  - pattern: ^$
    output: 'HTTP/1.1 200 OK\r\n\n'
    file: 'configs/CVE-2020-3452/mst.txt'
    next: _END
  # http-200-oem state collects input until it gets a blank line and then
  # returns content
  http-200-oem:
  - pattern: ^$
    output: 'HTTP/1.1 200 OK\r\n\n'
    file: 'configs/CVE-2020-3452/oem.txt'
    next: _END
  # http-404 state collects input until it gets a blank line and then
  # returns a 404 error.
  http-404:
  - pattern: ^$
    output: 'HTTP/1.1 404 Not found\r\n\n'
    next: _END
  # Shared state has some rules for ignoring known dynamic host headers when
  # calculating the request signature.
  _SHARED:
  # Ignore Host headers because we know they'll be different for every
  # destination honeypot.
  - pattern: '^Host:'
    tags:
    - am_ignore
  # Ignore CSeq and Content-Length because they also vary.
  - pattern: '^CSeq:'
    tags:
    - am_ignore
  - pattern: '^Content-Length:'
    tags:
    - am_ignore
